// libraries/design-lab-system/components/atoms/actions/Button/Button.preview.tsx
const previewStyles = String.raw`
.preview-button-sheet {
  width: 172px;
  height: 96px;
  position: relative;
  padding: 14px;
  box-sizing: border-box;
  display: flex;
  align-content: center;
  align-items: center;
  justify-content: flex-start;
  flex-wrap: wrap;
  gap: 8px;
}
.preview-button {
  width: auto;
  height: 32px;
  padding: 0 13px;
  border-radius: var(--corner-control);
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: 8px;
  font-style: normal;
  font-weight: 700;
  letter-spacing: 0.01em;
}
.preview-button--primary {
  min-width: 82px;
  background: var(--color-accent-primary);
  color: var(--color-canvas);
  box-shadow: 0 5px 12px color-mix(in srgb, var(--color-accent-primary) 18%, transparent);
}
.preview-button--secondary {
  min-width: 70px;
  border: 1px solid var(--color-border-strong);
  background: var(--color-surface-secondary);
  color: var(--color-text-primary);
}
.preview-button--ghost {
  width: 32px;
  padding: 0;
  border: 1px solid transparent;
  color: var(--color-text-muted);
  justify-content: center;
  letter-spacing: 0.08em;
}
.preview-button b {
  font-size: 11px;
  font-weight: 500;
  line-height: 1;
}
`
export function ButtonPreview() {
  return (
    <>
      <style>{previewStyles}</style>
      <div className="preview-button-sheet" role="img" aria-label="Button variants illustration">
        <span className="preview-button preview-button--primary">
          <b>＋</b>Create
        </span>
        <span className="preview-button preview-button--secondary">Cancel</span>
        <span className="preview-button preview-button--ghost" aria-hidden="true">
          •••
        </span>
      </div>
    </>
  )
}

// libraries/nuxt-ui-system/components/actions/Button/Button.preview.vue
<template>
  <div class="nuxt-button-preview" aria-hidden="true">
    <span class="nuxt-button-preview__primary">Continue</span>
    <span class="nuxt-button-preview__secondary">Back</span>
  </div>
</template>

<style scoped>
.nuxt-button-preview {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  width: 100%;
  height: 100%;
  color: var(--ds-color-text-primary);
  font: 600 12px/1 var(--ds-typography-interface-family);
}

.nuxt-button-preview span {
  display: inline-flex;
  align-items: center;
  min-height: 34px;
  padding: 0 14px;
  border-radius: var(--ds-corner-control);
}

.nuxt-button-preview__primary {
  color: var(--ds-color-canvas);
  background: var(--ds-color-accent-primary);
}

.nuxt-button-preview__secondary {
  border: 1px solid var(--ds-color-border-default);
  background: var(--ds-color-surface-primary);
}
</style>
