// libraries/northstar-travel-system/components/atoms/actions/Button/Button.preview.tsx
const previewStyles = String.raw`
.northstar-button-preview {
  width: 100%;
  display: grid;
  place-items: center;
}

.northstar-button-preview span {
  min-height: 40px;
  padding: 0 18px;
  border-radius: var(--radius-small);
  background: var(--color-accent-primary);
  color: var(--color-canvas);
  display: inline-flex;
  align-items: center;
  font-size: 12px;
  font-weight: 700;
}
`

export function ButtonPreview() {
  return (
    <div className="northstar-button-preview">
      <style>{previewStyles}</style>
      <span>Search flights</span>
    </div>
  )
}

// libraries/nuxt-ui-system/components/actions/Button/Button.preview.vue
<template>
  <div class="nuxt-button-preview" aria-hidden="true">
    <span class="nuxt-button-preview__primary">Continue</span>
    <span class="nuxt-button-preview__secondary">Back</span>
  </div>
</template>

<style scoped>
.nuxt-button-preview {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  width: 100%;
  height: 100%;
  color: var(--ds-color-text-primary);
  font: 600 12px/1 var(--ds-typography-interface-family);
}

.nuxt-button-preview span {
  display: inline-flex;
  align-items: center;
  min-height: 34px;
  padding: 0 14px;
  border-radius: var(--ds-corner-control);
}

.nuxt-button-preview__primary {
  color: var(--ds-color-canvas);
  background: var(--ds-color-accent-primary);
}

.nuxt-button-preview__secondary {
  border: 1px solid var(--ds-color-border-default);
  background: var(--ds-color-surface-primary);
}
</style>
